### ISSUE TITLE
HEADSHOTS

### ISSUE THREAD

**Issue by RoniPunk** [EmeraldCoasttt/BrutalDoomPlatinum#23]
Can not pull of headshots. Aim at head shot doesn't register. Headshot use to explode. Aim rifle straight at face goes right through nothing happens. 

GZDoom 4.10.0

**Comment by EmeraldCoasttt** [comment]
Can't replicate (Are you confusing the revolver and railgun's special headshot damage?)

**Comment by RoniPunk** [comment]
No, in 3.0 when you shot a monster and it didn't gib or die. Sometimes would scream in pain or fire back and you would be able to shot a head shot a receive a health bonus or armor bonus. In 3.1 and after in both my main DOOM wad and both WADsmoosh. the head shots do not work. I am using gzDOOM 4.10.0. Keep up with the great work!

**Comment by RoniPunk** [comment]
I just fixed this. DECORATE\GORE\Head_Sys.txt Works like 3.0.

**Comment by Agitatio** [comment]
Still an issue even in 4.0. Mostly on Riflemen. It's like their head doesn't exist. Shots go right through.
